name: Build

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        make venv
    - name: Build figures
      run: make all -j 3
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: files
        path: |
          output/*.svg
