name: Test

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        make venv
    - name: Test with pytest
      run: |
        . venv/local/bin/activate && pytest --cov=syserol --cov-report=xml --cov-config=.github/workflows/coveragerc
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
